import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
import SessionProvider from '../../src/components/SessionProvider'
import TanstackProviders from '@/tanstack/TanstackProviders'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <html lang='en'>
      <body
        className={
          inter.className +
          ' overflow-hidden max-h-screen h-screen max-w-[100vw] bg-white'
        }
      >
        <TanstackProviders>
          <SessionProvider session={session}>{children}</SessionProvider>
        </TanstackProviders>
      </body>
    </html>
  )
}
