import CalendarView from '@/components/CalendarView'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={
          inter.className +
          ' overflow-hidden max-h-screen h-screen max-w-[100vw] bg-white'
        }
      >
        <div className='flex h-full'>
          <CalendarView />
          {children}
        </div>
      </body>
    </html>
  )
}
